# config/football_columns.yaml
# Mapping from Football-Data.co.uk column names -> your canonical schema
# Edit values on the right if you want different target names.

column_map:
  # --- identity, result & meta ---
  Div: DIV
  Date: Date
  Time: Time
  HomeTeam: HOME
  AwayTeam: AWAY
  FTHG: FT_HOME_GOALS
  FTAG: FT_AWAY_GOALS
  FTR: FT_RESULT
  HTHG: HT_GOME_GOALS          # (kept your exact column name)
  HTAG: HT_AWAY_GOALS
  HTR: HT_RESULT
  Referee: REF

#  ----------------- Stats
  HS: HOME_SHOTS
  AS: AWAY_SHOTS
  HST: HOME_SOT
  AST: AWAY_SOT
  HF: HOME_FOUL
  AF: AWAY_FOUL
  HC: HOME_CORNER
  AC: AWAY_CORNER
  HY: HOME_YELLOW
  AY: AWAY_YELLOW
  HR: HOME_RED
  AR: AWAY_RED

  # --- pre-match 1X2 odds (by bookmaker) ---
  B365H: ODDS_B365_HOME
  B365D: ODDS_B365_DRAW
  B365A: ODDS_B365_AWAY

  BFDH: ODDS_BETFRED_HOME
  BFDD: ODDS_BETFRED_DRAW
  BFDA: ODDS_BETFRED_AWAY

  BMGMH: ODDS_BETMGM_HOME
  BMGMD: ODDS_BETMGM_DRAW
  BMGMA: ODDS_BETMGM_AWAY

  BVH: ODDS_BETVICTOR_HOME
  BVD: ODDS_BETVICTOR_DRAW
  BVA: ODDS_BETVICTOR_AWAY

  BWH: ODDS_BETWIN_HOME
  BWD: ODDS_BETWIN_DRAW
  BWA: ODDS_BETWIN_AWAY

  CLH: ODDS_CORAL_HOME
  CLD: ODDS_CORAL_DRAW
  CLA: ODDS_CORAL_AWAY

  LBH: ODDS_LADBROKES_HOME
  LBD: ODDS_LADBROKES_DRAW
  LBA: ODDS_LADBROKES_AWAY

  PSH: ODDS_PINNACLE_HOME
  PSD: ODDS_PINNACLE_DRAW
  PSA: ODDS_PINNACLE_AWAY

  # Betfair Exchange (pre)
  BFEH: ODDS_BFEX_HOME
  BFED: ODDS_BFEX_DRAW
  BFEA: ODDS_BFEX_AWAY

  # Market aggregates (pre)
  MaxH: ODDS_MAX_HOME
  MaxD: ODDS_MAX_DRAW
  MaxA: ODDS_MAX_AWAY
  AvgH: ODDS_AVG_HOME
  AvgD: ODDS_AVG_DRAW
  AvgA: ODDS_AVG_AWAY

  # --- pre-match totals (over/under 2.5) ---
  "B365>2.5": TOTALS_B365_OVER_2_5
  "B365<2.5": TOTALS_B365_UNDER_2_5
  "P>2.5": TOTALS_PINNACLE_OVER_2_5
  "P<2.5": TOTALS_PINNACLE_UNDER_2_5
  "Max>2.5": TOTALS_MAX_OVER_2_5
  "Max<2.5": TOTALS_MAX_UNDER_2_5
  "Avg>2.5": TOTALS_AVG_OVER_2_5
  "Avg<2.5": TOTALS_AVG_UNDER_2_5
  "BFE>2.5": TOTALS_BFEX_OVER_2_5
  "BFE<2.5": TOTALS_BFEX_UNDER_2_5

  # --- pre-match asian handicap (market line + prices) ---
  AHh: AH_LINE
  B365AHH: AH_B365_HOME
  B365AHA: AH_B365_AWAY
  PAHH: AH_PINNACLE_HOME
  PAHA: AH_PINNACLE_AWAY
  MaxAHH: AH_MAX_HOME
  MaxAHA: AH_MAX_AWAY
  AvgAHH: AH_AVG_HOME
  AvgAHA: AH_AVG_AWAY
  BFEAHH: AH_BFEX_HOME
  BFEAHA: AH_BFEX_AWAY

  # --- closing 1X2 odds ---
  B365CH: CLOSING_B365_HOME
  B365CD: CLOSING_B365_DRAW
  B365CA: CLOSING_B365_AWAY

  BFDCH: CLOSING_BETFRED_HOME
  BFDCD: CLOSING_BETFRED_DRAW
  BFDCA: CLOSING_BETFRED_AWAY

  BMGMCH: CLOSING_BETMGM_HOME
  BMGMCD: CLOSING_BETMGM_DRAW
  BMGMCA: CLOSING_BETMGM_AWAY

  BVCH: CLOSING_BETVICTOR_HOME
  BVCD: CLOSING_BETVICTOR_DRAW
  BVCA: CLOSING_BETVICTOR_AWAY

  BWCH: CLOSING_BETWIN_HOME
  BWCD: CLOSING_BETWIN_DRAW
  BWCA: CLOSING_BETWIN_AWAY

  CLCH: CLOSING_CORAL_HOME
  CLCD: CLOSING_CORAL_DRAW
  CLCA: CLOSING_CORAL_AWAY

  LBCH: CLOSING_LADBROKES_HOME
  LBCD: CLOSING_LADBROKES_DRAW
  LBCA: CLOSING_LADBROKES_AWAY

  PSCH: CLOSING_PINNACLE_HOME
  PSCD: CLOSING_PINNACLE_DRAW
  PSCA: CLOSING_PINNACLE_AWAY

  MaxCH: CLOSING_MAX_HOME
  MaxCD: CLOSING_MAX_DRAW
  MaxCA: CLOSING_MAX_AWAY
  AvgCH: CLOSING_AVG_HOME
  AvgCD: CLOSING_AVG_DRAW
  AvgCA: CLOSING_AVG_AWAY

  BFECH: CLOSING_BFEX_HOME
  BFECD: CLOSING_BFEX_DRAW
  BFECA: CLOSING_BFEX_AWAY

  # --- closing totals (over/under 2.5) ---
  "B365C>2.5": CLOSING_TOTALS_B365_OVER_2_5
  "B365C<2.5": CLOSING_TOTALS_B365_UNDER_2_5
  "PC>2.5": CLOSING_TOTALS_PINNACLE_OVER_2_5
  "PC<2.5": CLOSING_TOTALS_PINNACLE_UNDER_2_5
  "MaxC>2.5": CLOSING_TOTALS_MAX_OVER_2_5
  "MaxC<2.5": CLOSING_TOTALS_MAX_UNDER_2_5
  "AvgC>2.5": CLOSING_TOTALS_AVG_OVER_2_5
  "AvgC<2.5": CLOSING_TOTALS_AVG_UNDER_2_5
  "BFEC>2.5": CLOSING_TOTALS_BFEX_OVER_2_5
  "BFEC<2.5": CLOSING_TOTALS_BFEX_UNDER_2_5

  # --- closing asian handicap ---
  AHCh: CLOSING_AH_LINE
  B365CAHH: CLOSING_AH_B365_HOME
  B365CAHA: CLOSING_AH_B365_AWAY
  PCAHH: CLOSING_AH_PINNACLE_HOME
  PCAHA: CLOSING_AH_PINNACLE_AWAY
  MaxCAHH: CLOSING_AH_MAX_HOME
  MaxCAHA: CLOSING_AH_MAX_AWAY
  AvgCAHH: CLOSING_AH_AVG_HOME
  AvgCAHA: CLOSING_AH_AVG_AWAY
  BFECAHH: CLOSING_AH_BFEX_HOME
  BFECAHA: CLOSING_AH_BFEX_AWAY